import os
import requests

def write(username, name, age, university, course, work, company, nick_name, country, photo, about, linkedin, instagram, youtube, twitter, dribble, google, twitch, quora, codepen, deviantart, facebook, medium, slack, angularjs, apache, arduino, bash, bootstarp, c, canva, coffeescript, cplusplus, csharp, css, d3js, dart, django, docker, electron, figma, flask, flutter, gimp, git, go, googlecloud, graphql, haskell, heroku, html5, java, javascript, julia, jupyter, kotlin, linux, lua, markdown, mongodb, mysql, nextjs, nodejs, numpy, pandas, php, postgresql, python, raspberrypi, react, rust, sass, scikitlearn, swift, tailwind, tensorflow, cript, unity, vuejs, project_1_name, project_1_link, project_2_name, project_2_link, project_3_name, project_3_link, project_4_name, project_4_link, project_5_name, project_5_link):
    try:
        os.mkdir(f"storage/{username}")
    except:
        pass
    with open(f"storage/{username}/{username}.txt", "w") as f:
        f.write(f"""
            {username}
            {name}
            {age}
            {university}
            {course}
            {work}
            {company}
            {nick_name}
            {country}
            {photo}
            {about}
            {linkedin}
            {instagram}
            {youtube}
            {twitter}
            {dribble}
            {google}
            {twitch}
            {quora}
            {codepen}
            {deviantart}
            {facebook}
            {medium}
            {slack}
            {angularjs}
            {apache}
            {arduino}
            {bash}
            {bootstarp}
            {c}
            {canva}
            {coffeescript}
            {cplusplus}
            {csharp}
            {css}
            {d3js}
            {dart}
            {django}
            {docker}
            {electron}
            {figma}
            {flask}
            {flutter}
            {gimp}
            {git}
            {go}
            {googlecloud}
            {graphql}
            {haskell}
            {heroku}
            {html5}
            {java}
            {javascript}
            {julia}
            {jupyter}
            {kotlin}
            {linux}
            {lua}
            {markdown}
            {mongodb}
            {mysql}
            {nextjs}
            {nodejs}
            {numpy}
            {pandas}
            {php}
            {postgresql}
            {python}
            {raspberrypi}
            {react}
            {rust}
            {sass}
            {scikitlearn}
            {swift}
            {tailwind}
            {tensorflow}
            {cript}
            {unity}
            {vuejs}
            {project_1_name}
            {project_1_link}
            {project_2_name}
            {project_2_link}
            {project_3_name}
            {project_3_link}
            {project_4_name}
            {project_4_link}
            {project_5_name}
            {project_5_link}
        """)
    cover_photo = requests.get(photo)
    with open(f"storage/{username}/cover_photo.jpg", "wb") as f:
        f.write(cover_photo.content)